version: "3"
services:
  publisher:
    build: ./publisher
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - db
    ports:
      - "5500:5432"
    environment:
      - REP_DB=rep_test
      - REP_USER=rep_user
      - REP_PASSWORD=rep_password
      - REP_PUB_NAME=rep_test_pub
  subscriber:
    build: ./subscriber
    networks:
      - db
    ports:
      - "5501:5432"
    environment:
      - REP_DB=rep_test
      - REP_USER=rep_user
      - REP_PASSWORD=rep_password
      - REP_PUB_NAME=rep_test_pub
      - REP_SUB_NAME=rep_test_sub
networks:
  db:
